name: makhber
summary: Makhber
description: |
  Application for Visualization and Analysis of Scientific Data
icon: makhber/icons/com.github.makhber.Makhber.svg
base: core20
compression: lzo
grade: stable
confinement: strict
adopt-info: makhber
architectures:
  - build-on: amd64 

apps:
  makhber:
    common-id: com.github.makhber.Makhber
    command: usr/bin/makhber
    environment:
      PYTHONPATH: $SNAP/lib/python3.8/site-packages:$SNAP/usr/share/makhber
    extensions:
      - kde-neon
    plugs:
      - home
      - network
      - removable-media
      - unity7

parts:
  makhber:
    source-type: local
    source: .
    parse-info: [usr/share/appdata/com.github.makhber.Makhber.appdata.xml]
    plugin: cmake
    cmake-parameters: 
      - "-DCMAKE_INSTALL_PREFIX=/usr"
      - "-DCMAKE_BUILD_TYPE=Release"
      - "-DMAKHBER_SEARCH_FOR_UPDATES=OFF"
      - "-DCMAKE_PREFIX_PATH=$SNAPCRAFT_STAGE/usr"
      - "-DMAKHBER_SCRIPTING_PYTHON=ON"
      - "-DPyQt_INCLUDE_DIR=$SNAPCRAFT_STAGE/lib/python3.8/site-packages/PyQt5/bindings"
    build-environment:
      - PATH: $HOME/.local/bin:$PATH
      - LD_LIBRARY_PATH: /snap/kde-frameworks-5-qt-5-15-core20-sdk/current/usr/lib/x86_64-linux-gnu:$LD_LIBARARY_PATH
      - PYTHONPATH: $SNAPCRAFT_STAGE/lib/python3.8/site-packages
    build-packages:
      - g++
      - make
      - libglu1-mesa
      - git
    stage-packages:
      - libpython3.8
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags)"
    after:
      - gsl
      - muparser
      - pyqt5
      - pyqt5-sip
  gsl:
    source-type: tar
    source: https://ftp.gnu.org/gnu/gsl/gsl-2.6.tar.gz
    source-checksum: sha256/b782339fc7a38fe17689cb39966c4d821236c28018b6593ddb6fd59ee40786a8
    plugin: autotools
    autotools-configure-parameters:
      - "--disable-static"
      - "--prefix=/usr"
    build-packages:
      - g++
    prime:
      - -usr/bin
      - -usr/include
      - -usr/lib/*.la
      - -usr/lib/pkgconfig
      - -usr/share
  muparser:
    source-type: tar
    source: https://github.com/beltoforion/muparser/archive/v2.3.2.tar.gz
    source-checksum: sha256/b35fc84e3667d432e3414c8667d5764dfa450ed24a99eeef7ee3f6647d44f301
    plugin: cmake
    cmake-parameters:
      - "-DCMAKE_BUILD_TYPE=Release"
      - "-DCMAKE_INSTALL_PREFIX=/usr"
    build-packages:
      - g++
    prime:
      - -usr/include
      - -usr/lib/x86_64-linux-gnu/pkgconfig
  pyqt5:
    source-type: tar
    source: https://pypi.python.org/packages/source/P/PyQt5/PyQt5-5.15.4.tar.gz
    source-checksum: sha256/2a69597e0dd11caabe75fae133feca66387819fc9bc050f547e5551bce97e5be
    plugin: make
    build-packages:
      - g++
      - libgl-dev
      - python3-pip
    build-environment:
      - PATH: $HOME/.local/bin:$PATH
      - LD_LIBRARY_PATH: /snap/kde-frameworks-5-qt-5-15-core20-sdk/current/usr/lib/x86_64-linux-gnu:$LD_LIBARARY_PATH
    override-build: |
      pip3 install sip pyqt-builder
      cd $SNAPCRAFT_PART_SRC
      sip-build --confirm-license \
        --build-dir ../build \
        --target-dir $SNAPCRAFT_PART_INSTALL/lib/python3.8/site-packages \
        --qmake=/snap/kde-frameworks-5-qt-5-15-core20-sdk/current/usr/lib/qt5/bin/qmake \
        --api-dir=$SNAPCRAFT_PART_INSTALL/usr/share/qt5/qsci/api/python \
        --concatenate 1 \
        --no-make \
        --no-designer-plugin \
        --no-qml-plugin \
        --no-tools \
        --disable QtQml \
        --disable QtBluetooth \
        --disable QtDBus \
        --disable QtDesigner \
        --disable QtHelp \
        --disable QtMultimedia \
        --disable QtMultimediaWidgets \
        --disable QtNfc \
        --disable QtPositioning \
        --disable QtLocation \
        --disable QtQuick \
        --disable QtQuickWidgets \
        --disable QtSensors \
        --disable QtSerialPort \
        --disable QtSql \
        --disable QtTest \
        --disable QtWebChannel \
        --disable QtWebKit \
        --disable QtWebKitWidgets \
        --disable QtWebSockets \
        --disable QtX11Extras \
        --disable QtXml \
        --disable QtXmlPatterns \
        --disable _QOpenGLFunctions_2_0 \
        --disable _QOpenGLFunctions_2_1 \
        --disable _QOpenGLFunctions_4_1_Core \
        --disable pylupdate \
        --disable pyrcc \
        --verbose
      cd $SNAPCRAFT_PART_BUILD
      snapcraftctl build
  pyqt5-sip:
    source-type: tar
    source: https://pypi.python.org/packages/source/P/PyQt5_sip/PyQt5_sip-12.9.0.tar.gz
    source-checksum: sha256/d3e4489d7c2b0ece9d203ae66e573939f7f60d4d29e089c9f11daa17cfeaae32
    plugin: python
    prime:
      - -bin/
      - -lib/python3.8/site-packages/_distutils*
      - -lib/python3.8/site-packages/pip*
      - -lib/python3.8/site-packages/pkg_resources*
      - -lib/python3.8/site-packages/wheel*
      - -lib/python3.8/site-packages/setuptools*
      - -share/python-wheels
