name: makhber
summary: Makhber
description: |
  Application for Visualization and Analysis of Scientific Data
base: core20
compression: lzo
grade: stable
confinement: strict
adopt-info: makhber
architectures:
  - build-on: amd64 

apps:
  makhber:
    common-id: com.github.makhber.Makhber
    command: usr/bin/makhber
    extensions:
      - kde-neon
    plugs:
      - home
      - network
      - removable-media
      - unity7

parts:
  makhber:
    source-type: local
    source: .
    parse-info: [usr/share/appdata/com.github.makhber.Makhber.appdata.xml]
    plugin: cmake
    cmake-parameters: 
      - "-DCMAKE_INSTALL_PREFIX=/usr"
      - "-DCMAKE_BUILD_TYPE=Release"
      - "-DMAKHBER_SEARCH_FOR_UPDATES=OFF"
      - "-DCMAKE_PREFIX_PATH=$SNAPCRAFT_STAGE/usr"
    build-packages:
      - g++
      - make
      - libglu1-mesa
      - git
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags)"
    after:
      - gsl
      - muparser
  gsl:
    source-type: tar
    source: https://ftp.gnu.org/gnu/gsl/gsl-2.6.tar.gz
    source-checksum: sha256/b782339fc7a38fe17689cb39966c4d821236c28018b6593ddb6fd59ee40786a8
    plugin: autotools
    autotools-configure-parameters:
      - "--disable-static"
      - "--prefix=/usr"
    build-packages:
      - g++
    prime:
      - -usr/bin
      - -usr/include
      - -usr/lib/*.la
      - -usr/lib/pkgconfig
      - -usr/share
  muparser:
    source-type: tar
    source: https://github.com/beltoforion/muparser/archive/v2.3.2.tar.gz
    source-checksum: sha256/b35fc84e3667d432e3414c8667d5764dfa450ed24a99eeef7ee3f6647d44f301
    plugin: cmake
    cmake-parameters:
      - "-DCMAKE_BUILD_TYPE=Release"
      - "-DCMAKE_INSTALL_PREFIX=/usr"
    build-packages:
      - g++
    prime:
      - -usr/include
      - -usr/lib/x86_64-linux-gnu/pkgconfig
